version: "3"
services:
  nginx:
    image: "nginx:alpine"
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./webroot:/var/www/html
    links:
      - backend:backend
      - app:app

  backend:
    image: "python:3.6-alpine"
    command: /bin/sh -xcv "pip install -r requirements.txt && FLASK_APP=backend/app.py FLASK_ENV=development flask run --reload --debugger -h 0.0.0.0 -p 8888"
    volumes:
      - ./:/opt/backend
    working_dir: /opt/backend

  app:
    build: frontend
    env_file: .env
    volumes:
      - ./frontend:/app
      - "/app/node_modules"
    command: yarn dev
